package com.onetuks.csphinxserver.domain.question;

public enum Topic {
  PROGRAMMING_LANGUAGE, // 프로그래밍 언어 (Java, Python, C++ 등)
  DATA_STRUCTURES, // 자료구조 (배열, 리스트, 트리, 그래프 등)
  ALGORITHMS, // 알고리즘 (정렬, 탐색, 그래프 등)
  DATABASES, // 데이터베이스 (SQL, NoSQL, 인덱스, 트랜잭션 등)
  OPERATING_SYSTEMS, // 운영체제 (메모리 관리, 프로세스, 스레드 등)
  NETWORKING, // 네트워크 (OSI 모델, TCP/IP, HTTP 등)
  SOFTWARE_ENGINEERING, // 소프트웨어 공학 (설계, 테스트, 소프트웨어 개발론 등)
  COMPUTER_ARCHITECTURE, // 컴퓨터 구조 (CPU, 메모리 구조, 캐시, 명령어 등)
  //  CLOUD_COMPUTING,        // 클라우드 컴퓨팅 (가상화, 클라우드 서비스, 분산 시스템 등)
  //  SECURITY,               // 보안 (암호화, 인증, 네트워크 보안 등)
  //  AI_ML,                  // 인공지능 및 머신러닝 (딥러닝, 지도학습, 비지도학습 등)
  //  IMAGE_PROCESSING,       // 영상 처리 (컴퓨터 비전, 이미지 필터링 등)
  SOFTWARE_TOOLS, // 소프트웨어 도구 (Git, Docker, CI/CD, IDE 등)
  //  DEVOPS,                 // 데브옵스 (CI/CD, 인프라 자동화, 모니터링 등)
  //  BIG_DATA,               // 빅데이터 (Hadoop, Spark, 데이터 분석 등)
  WEB_DEVELOPMENT, // 웹 개발 (HTML, CSS, JavaScript, 웹 보안 등)
  //  MOBILE_DEVELOPMENT,     // 모바일 개발 (Android, iOS, 반응형 디자인 등)
  //  CYBERSECURITY,          // 사이버 보안 (취약점, 네트워크 보안, 악성코드 등)
  //  EMBEDDED_SYSTEMS,       // 임베디드 시스템 (펌웨어, 하드웨어 통신, IoT 등)
  //  DATA_SCIENCE,           // 데이터 과학 (통계, 데이터 분석, 데이터 시각화 등)
  //  DISTRIBUTED_SYSTEMS     // 분산 시스템 (RPC, CAP 이론, 분산 파일 시스템 등)
}
