name: Pull Request Integration
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions: read-all

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    services:
      mysql-db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: csphinx
          MYSQL_USER: myroot
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      DB_HOST: mysql-db
      DB_USERNAME: myroot
      DB_PASSWORD: secret
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Build Filter
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            application:
              - '**/build.gradle'
              - '**/src/**'

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h "$DB_HOST" --silent;
            do echo "Waiting for MySQL on $DB_HOST..."
            sleep 2
          done
        shell: bash

      - name: Check Docker access
        run: |
          docker version
          docker ps -a

      - name: Gradlew exec permission grant
        if: steps.changes.outputs.application == 'true'
        run: chmod +x ./gradlew
        shell: bash

      - name: JDK Setup
        if: steps.changes.outputs.application == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
          cache: 'gradle'

      - name: Gradle Build
        if: steps.changes.outputs.application == 'true'
        env:
          APP_NAME: ${{ secrets.APP_NAME }}
          PROFILE: ${{ secrets.PROFILE }}
          CLOUD_CONFIG_URL: ${{ secrets.CLOUD_CONFIG_URL }}
          ACTUATOR_PORT: ${{ secrets.ACTUATOR_PORT }}
        run: |
          ./gradlew build \
            -Dspring.datasource.url=jdbc:mysql://$DB_HOST:3306/csphinx \
            -Dspring.datasource.username=$DB_USER \
            -Dspring.datasource.password=$DB_PASS \
            spotlessApply --parallel

      - name: Coverage Report
        if: steps.changes.outputs.application == 'true'
        uses: madrapps/jacoco-report@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage Report
          update-comment: true
          min-coverage-overall: 10
          min-coverage-changed-files: 10
          paths: |
            ${{ github.workspace }}/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml

  style-test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Build Filter
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            application:
              - '**/build.gradle'
              - '**/src/**'

      - name: JDK Setup
        if: steps.changes.outputs.application == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
          cache: 'gradle'

      - name: Style Check
        if: steps.changes.outputs.application == 'true'
        run: |
          ./gradlew spotlessCheck
